// ─── DESIGN TOKENS via CSS variables ─────────────────────────────────────────
// ALL colors reference CSS custom properties so dark/light mode works via
// a single [data-theme="light"] attribute on <html>.
export const C = {
    bg: "var(--bg)",
    surface: "var(--surface)",
    surface2: "var(--surface2)",
    accent: "var(--accent)",
    accentGlow: "var(--accent-glow)",
    text: "var(--text)",
    muted: "var(--muted)",
    border: "var(--border)",
    green: "var(--green)",
    red: "var(--red)",
    purple: "var(--purple)",
    btnText: "var(--btn-text)",
};

const styles = {
    app: {
        fontFamily: "'Inter', -apple-system, sans-serif",
        fontWeight: 400,
        background: "var(--bg)",
        color: "var(--text)",
        minHeight: "100vh",
        width: "100%",
    },
    container: {
        width: "100%",
        maxWidth: "520px",
        margin: "0 auto",
        padding: "20px 20px 110px 20px",
        paddingBottom: "calc(110px + env(safe-area-inset-bottom, 0px))",
        boxSizing: "border-box",
        overflowX: "hidden",
    },
    heading: {
        fontFamily: "'DM Sans', -apple-system, sans-serif",
        color: "var(--text)",
    },
    // Using a class mapping to inline styles if needed, but it's better to use className="clay-card".
    // I'll define these for fallback, but components should prefer className.
    card: {
        background: "var(--surface)",
        borderRadius: "var(--clay-radius, 24px)",
        boxShadow: "8px 8px 16px var(--clay-shadow), -8px -8px 16px var(--clay-highlight), inset 2px 2px 4px var(--clay-inner-highlight), inset -2px -2px 4px var(--clay-inner-shadow)",
        padding: "24px",
        marginBottom: "16px",
        boxSizing: "border-box",
        border: "none",
    },
    btn: {
        background: "var(--accent)",
        color: "var(--btn-text)",
        border: "none",
        borderRadius: "50px",
        padding: "14px 32px",
        fontFamily: "'Inter', -apple-system, sans-serif",
        fontSize: "13px",
        letterSpacing: "0.15em",
        textTransform: "uppercase",
        fontWeight: "600",
        cursor: "pointer",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "8px",
        boxShadow: "6px 6px 12px var(--clay-shadow), -6px -6px 12px var(--clay-highlight), inset 2px 2px 4px rgba(255,255,255,0.3), inset -2px -2px 4px rgba(0,0,0,0.1)",
    },
    btnOutline: {
        background: "var(--surface)",
        color: "var(--text)",
        border: "1px solid transparent",
        borderRadius: "50px",
        padding: "10px 20px",
        fontFamily: "'Inter', -apple-system, sans-serif",
        fontSize: "12px",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        cursor: "pointer",
        display: "inline-flex",
        alignItems: "center",
        justifyContent: "center",
        gap: "6px",
        boxShadow: "4px 4px 8px var(--clay-shadow), -4px -4px 8px var(--clay-highlight)",
        fontWeight: "500",
    },
    timerCircle: {
        width: "160px",
        height: "160px",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        flexDirection: "column",
        margin: "0 auto",
        position: "relative",
        borderRadius: "50%",
        background: "var(--surface)",
        boxShadow: "inset 8px 8px 16px var(--clay-shadow), inset -8px -8px 16px var(--clay-highlight)",
    },
    tag: {
        background: "var(--surface)",
        color: "var(--accent)",
        borderRadius: "50px",
        padding: "4px 12px",
        fontSize: "11px",
        letterSpacing: "0.1em",
        display: "inline-block",
        boxShadow: "inset 2px 2px 5px var(--clay-shadow), inset -2px -2px 5px var(--clay-highlight)",
    },
    label: {
        fontSize: "11px",
        letterSpacing: "0.2em",
        textTransform: "uppercase",
        color: "var(--muted)",
    },
};

export default styles;
